### ISSUE TITLE
UtahTransitSystems package contains wrong features

### ISSUE THREAD

**Issue by keatonwalker** [agrc/backseat-driver#16]
[UtahTransitSystems.json](https://github.com/agrc/backseat-driver/blob/master/packages/UtahTransitSystems.json) needs an updated `feature_classes` array. See https://github.com/agrc/gis.utah.gov/issues/774

**Comment by keatonwalker** [comment]
@gregbunce could you provide a list of features that should be in this package?

**Comment by steveoh** [comment]
Bus routes, commuter rail routes and stations, light rail and stations

**Comment by steveoh** [comment]
Did you get this sorted out?

**Comment by keatonwalker** [comment]
Today is my plan.
