### ISSUE TITLE
oil and gas wells not updating

### ISSUE THREAD

**Issue by ZachBeck** [agrc/backseat-driver#19]
last update to google drive download was 3/20/2018

**Comment by stdavis** [comment]
[It looks like it should be checked daily to me](https://github.com/agrc/backseat-driver/blob/a503be468bc3b785af0b653559ac3f995ba7d5c3/features/ENERGY_OilGasWells.json#L14). Is back seat driver a scheduled task on 58?

**Comment by steveoh** [comment]
I'm pretty sure it is scheduled on 58 but I don't know much about it

**Comment by stdavis** [comment]
Was this ever cleared up?

**Comment by stdavis** [comment]
It looks good to me: 
![image](https://user-images.githubusercontent.com/1326248/51325106-7034ca80-1a29-11e9-8098-3cbbcf23b691.png)

**Comment by keatonwalker** [comment]
The oil and gas wells are being updated.
