### ISSUE TITLE
Credentials file naming

### ISSUE THREAD

**Issue by keatonwalker** [agrc/backseat-driver#2]
Make oauth credentials file name unique to application

**Comment by steveoh** [comment]
Can you explain this? Are you referencing the service worker account in google or the client secrets json file?

**Comment by keatonwalker** [comment]
I am referencing the installed application oauth credentials created when the zip_loader acts as a user.  I was using a file name that was too generic and it was colliding with other applications I have built.

**Comment by steveoh** [comment]
> zip_loader acts as a user

Would this be the service account?

> a filename that was too generic

is this the `client_secrets.json` that is created from a service account?

**Comment by keatonwalker** [comment]
zip_loader.py is the main module with a CLI. 
This tool can run on behalf of a user using their google credentials and permissions or as a service account. I will list out the secrets and credentials by agent:

- User
  - client_secret.json
    - application secrets with things like a client id and google project id.
    - Must be distributed with the program to use installed application oauth flow .
  - oauth credentials
    - **This file is the one referenced by this issue.**
    - JWT with access and refresh tokens obtained through an oauth flow.
    - It may be stored with other JWTs and needs a name that is a least unique to this application.
    - name needs to be known so the file can be loaded when a run of zip_loader requires it.
    - Allows application to create folders and files owned by a user.
      - Creating files as a service account causes multiple problems.
- Service account
  - service_secret.json
  - Keys and credentials to use server to server oauth.
  - Must be distributed with the program to update files as the service account.

**Comment by keatonwalker** [comment]
I changed this to be have a file name specific to the drive-loader google project.
